name: Terraform Apply on Merge

on:
  push:
    branches:
      - master

jobs:
  terraform-apply:
    name: Terraform Plan and Apply
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa.pub
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.2

      - name: Export Azure Environment Variables
        run: |
          echo "ARM_CLIENT_ID=${{ secrets.ARM_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ secrets.ARM_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }}" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: terraform

      - name: Generate Inventory File
        run: |
          PUBLIC_IP=$(terraform output -raw public_ip_address)
          echo "Resolved PUBLIC_IP: $PUBLIC_IP" # Debug step to verify the output
          cat <<EOT > ansible/inventory.ini
          [flask_servers]
          $PUBLIC_IP ansible_user=flaskappuser ansible_ssh_private_key_file=~/.ssh/id_rsa
          EOT
        working-directory: terraform

      - name: Echo Inventory File Contents
        run: |
          echo "Contents of inventory.ini:"
          cat ansible/inventory.ini

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Run Ansible Playbook
        run: ansible-playbook -i ansible/inventory.ini ansible/flask-playbook.yml -e "tmdb_api_key=${{ secrets.TMDB_API_KEY }}"


