name: Lint Python Code

on:
  push:
    branches:
      - feature/*

jobs:
  pylint:
    name: Lint Python Code
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.12

      - name: Install pylint
        run: pip install pylint

      - name: Install Dependencies
        run: pip install -r flask-app/requirements.txt

      - name: Run pylint
        run: pylint flask-app/*.py

  create-pr:
    name: Create Pull Request
    needs: pylint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Apply lint fixes
          branch: lint-auto-fix
          base: main
          title: "Auto-created PR: ${{ env.commit_message }}"
          body: |
            Lint Tests Passsed